import { createAdminClient } from '@/lib/supabase/admin'
import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

function noStore(payload: unknown, status = 200) {
  return NextResponse.json(payload, {
    status,
    headers: { 'Cache-Control': 'no-store, no-cache, must-revalidate', Pragma: 'no-cache' },
  })
}

async function checkAdmin() {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user || user.email !== process.env.ADMIN_EMAIL) return null
  return user
}

export async function POST(
  _req: NextRequest,
  { params }: { params: { id: string } }
) {
  const user = await checkAdmin()
  if (!user) {
    return noStore({ error: 'Niet geautoriseerd' }, 401)
  }

  const clientId = params.id
  const admin = createAdminClient()

  // Verify client exists
  const { data: client, error: clientError } = await admin
    .from('clients')
    .select('id, company, name, email')
    .eq('id', clientId)
    .single()

  if (clientError || !client) {
    return noStore({ error: 'Klant niet gevonden' }, 404)
  }

  // Insert new token (token value is generated by DB default)
  const { data: tokenRow, error: insertError } = await admin
    .from('intake_tokens')
    .insert({ client_id: clientId })
    .select('token, expires_at')
    .single()

  if (insertError || !tokenRow) {
    return noStore(
      { error: 'Token aanmaken is mislukt: ' + (insertError?.message ?? 'onbekende fout') },
      500
    )
  }

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://portal.brandiscode.com'
  const url = `${baseUrl}/intake/${tokenRow.token}`

  // Backward compatibility: keep invitation fields present,
  // but this endpoint no longer sends e-mail.
  return noStore({
    token: tokenRow.token,
    url,
    expires_at: tokenRow.expires_at,
    invitation_sent: false,
    warnings: [
      'Deze endpoint verstuurt geen intake-uitnodiging meer. Gebruik /api/admin/clients/[id]/intake-token/send-invitation om de mail te versturen.',
    ],
  })
}
