import { createAdminClient } from '@/lib/supabase/admin'
import { createClient } from '@/lib/supabase/server'
import { NextRequest, NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

async function checkAdmin() {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user || user.email !== process.env.ADMIN_EMAIL) return null
  return user
}

export async function POST(
  _req: NextRequest,
  { params }: { params: { id: string } }
) {
  const user = await checkAdmin()
  if (!user) {
    return NextResponse.json(
      { error: 'Niet geautoriseerd' },
      { status: 401, headers: { 'Cache-Control': 'no-store' } }
    )
  }

  const clientId = params.id
  const admin = createAdminClient()

  // Verify client exists
  const { data: client, error: clientError } = await admin
    .from('clients')
    .select('id, company, name')
    .eq('id', clientId)
    .single()

  if (clientError || !client) {
    return NextResponse.json(
      { error: 'Klant niet gevonden' },
      { status: 404, headers: { 'Cache-Control': 'no-store' } }
    )
  }

  // Insert new token (token value is generated by DB default)
  const { data: tokenRow, error: insertError } = await admin
    .from('intake_tokens')
    .insert({ client_id: clientId })
    .select('token, expires_at')
    .single()

  if (insertError || !tokenRow) {
    return NextResponse.json(
      { error: 'Token aanmaken is mislukt: ' + (insertError?.message ?? 'onbekende fout') },
      { status: 500, headers: { 'Cache-Control': 'no-store' } }
    )
  }

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://portal.brandiscode.com'
  const url = `${baseUrl}/intake/${tokenRow.token}`

  return NextResponse.json(
    { token: tokenRow.token, url, expires_at: tokenRow.expires_at },
    { headers: { 'Cache-Control': 'no-store' } }
  )
}
