import { createAdminClient } from '@/lib/supabase/admin'
import { createClient } from '@/lib/supabase/server'
import { Resend } from 'resend'
import { buildIntakeInvitationEmail } from '@/lib/onboardingEmails.mjs'
import { NextRequest, NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

function generateTemporaryPassword(): string {
  const chars = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789'
  return Array.from({ length: 12 }, () => chars[Math.floor(Math.random() * chars.length)]).join('')
}

async function checkAdmin() {
  const supabase = createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user || user.email !== process.env.ADMIN_EMAIL) return null
  return user
}

export async function POST(
  _req: NextRequest,
  { params }: { params: { id: string } }
) {
  const user = await checkAdmin()
  if (!user) {
    return NextResponse.json(
      { error: 'Niet geautoriseerd' },
      { status: 401, headers: { 'Cache-Control': 'no-store' } }
    )
  }

  const clientId = params.id
  const admin = createAdminClient()

  // Verify client exists
  const { data: client, error: clientError } = await admin
    .from('clients')
    .select('id, company, name, email')
    .eq('id', clientId)
    .single()

  if (clientError || !client) {
    return NextResponse.json(
      { error: 'Klant niet gevonden' },
      { status: 404, headers: { 'Cache-Control': 'no-store' } }
    )
  }

  // Insert new token (token value is generated by DB default)
  const { data: tokenRow, error: insertError } = await admin
    .from('intake_tokens')
    .insert({ client_id: clientId })
    .select('token, expires_at')
    .single()

  if (insertError || !tokenRow) {
    return NextResponse.json(
      { error: 'Token aanmaken is mislukt: ' + (insertError?.message ?? 'onbekende fout') },
      { status: 500, headers: { 'Cache-Control': 'no-store' } }
    )
  }

  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://portal.brandiscode.com'
  const url = `${baseUrl}/intake/${tokenRow.token}`

  const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null
  const warnings: string[] = []
  let invitationSent = false

  if (!resend) {
    warnings.push('E-mailprovider is niet geconfigureerd (RESEND_API_KEY ontbreekt). Intake-uitnodiging is niet verstuurd.')
  } else if (client.company || client.name) {
    const mainEmail = client.email ?? null
    if (mainEmail) {
      try {
        const temporaryPassword = generateTemporaryPassword()
        const authUser = await admin.auth.admin.createUser({
          email: mainEmail,
          email_confirm: true,
          password: temporaryPassword,
          user_metadata: { name: client.name, company: client.company },
        })

        const alreadyRegistered = Boolean(authUser.error?.message.includes('already been registered'))
        const { subject, html } = buildIntakeInvitationEmail({
          name: client.name ?? client.company ?? 'Klant',
          company: client.company ?? client.name,
          email: mainEmail,
          intakeUrl: url,
          isExistingUser: alreadyRegistered,
          temporaryPassword: alreadyRegistered ? undefined : temporaryPassword,
        })

        await resend.emails.send({
          from: process.env.EMAIL_FROM ?? 'Brand is Code <noreply@brandiscode.com>',
          to: mainEmail,
          subject,
          html,
        })
        invitationSent = true
      } catch (error) {
        warnings.push(`Intake-uitnodiging versturen naar hoofdaccount mislukt: ${String(error)}`)
      }
    }
  }

  return NextResponse.json(
    {
      token: tokenRow.token,
      url,
      expires_at: tokenRow.expires_at,
      invitation_sent: invitationSent,
      ...(warnings.length ? { warnings } : {}),
    },
    { headers: { 'Cache-Control': 'no-store' } }
  )
}
